### PR TITLE
[feature] enforce date with timezome

### PR DESCRIPTION
**Pull request by valydia**
Addressed the [issue 54](https://github.com/digital-preservation/csv-validator/issues/54)

### CODE REVIEW

**Comment by adamretter** [comment]
@valy without the ability to distinguish this as a 1.1 feature, you are actually causing a regression in 1.0 compatibility just as you did with the changes for `range`.

I don't want to merge this as you are actually deleting code that we will have to later restore...

**Comment by valydia** [comment]
@adamretter 
This PR is the implementation of a new feature and not the improvement of an existing one.  
So the column rule xDateTime still exits, but now we have the rule xDateTimeWithTimeZone that will rejects the date time without timezone. The behaviour of the xDateTime hasn't changed, it accepts date time with or without timezone. No code has actually been deleted.

**Comment by adamretter** [comment]
@valydia :-) Ah okay, my mistake.

**Comment by DavidUnderdown** [comment]
May be better to raise this somewhere else, but considering updating the the csv-schema docs and EBNF, any thoughts on whether it would be better to maintain the numbering in the original EBNF http://digital-preservation.github.io/csv-schema/csv-schema-1.0.html#dfn-ebnf-schema and add the new features at new numbers, (out of order?), or renumber from scratch to put the new tests in logical places? ie lgoically it would make sense to put the new xDateTimeWithTimeZone with the original xDateTime http://digital-preservation.github.io/csv-schema/csv-schema-1.0.html#dfn-ebnf-xsd-date-time-expr but the next available unused number is 81

**Comment by adamretter** [comment]
In version 1.1 of the CSV-Schema it would be better to renumber, i.e. the rules should appear in a logical and correct order.

**Comment by DavidUnderdown** [comment]
To me this seems to add quite a lot of maintenance overhead where rules are renumbered in different versions as the developers will need to create more of a mapping between rules that are functionally identical in different schema versions, but numbered differently - come to that to what extent should the documentation refer back to the previous version?

**Comment by adamretter** [comment]
My point is that the EBNF is the authority. EBNF itself has an ordering and when reading it there is a natural progression, we should keep the EBNF easy to read and naturally readable. If you want an example compare the EBNF of XQuery 1.0 against XQuery 3.0.

**Comment by DavidUnderdown** [comment]
http://digital-preservation.github.io/csv-schema/csv-schema-1.1.html draft is now up.  Comments welcome, particularly on the detail of the EBNF

**Pull request merged**
