### PR TITLE
Update dependencies to latest, requires Scala 2.12 and Java 1.8

### PR DESCRIPTION
**Pull request by adamretter**
This should put us in a good place to support Java 9 (shortly when Scala supports it) and also to further improve the performance of both the CSV Parser and the CSV Schema Parser.

We could also now create a better GUI for the UI using ScalaFX (JavaFX requires Java 8).

### CODE REVIEW

**Comment by adamretter** [comment]
@DavidUnderdown It's been almost 1 year! Any updates on this? I would love to see some of this stuff merged...

**Comment by adamretter** [comment]
I spent some time updating this for Scala 2.13. It is almost ready I think, just 4 failing tests to track down.

**Comment by seanhenry1996** [comment]
Hi @adamretter, thanks for this fix! i see this was merged recently. Is there a new version number available for this fix?

**Comment by DavidUnderdown** [comment]
Hi @seanhenry1996 there's some wider work on updating going on at the moment. Should be an official new release in a week or so.

**Comment by DavidUnderdown** [comment]
Hi Sean

It will be down to whatever underlying regex library the validator is using (we don't specify to that level in the schema language definition). So I imagine the validator is not supporting the slightly more esoteric non-capturing groups you've introduced. I'm not sure that in the use case of the CSV Validator there'd really be a difference between a capturing and a non-capturing group anyway?

**Comment by luketebbs** [comment]
@seanhenry1996 - are you able to help me reproduce this problem? 

I just tried the following with the CLI version, 1.2-RC4 - 

schema - 
```
version 1.0
@totalColumns 1
LastName: regex("^(?:(?:^|,)(AAA|BBB|CCC))+$")
```

data - 
```
LastName
AAA
blah
"BBB,CCC"
```

And it worked as I'd expect - 

```
Error:   regex("^(?:(?:^|,)(AAA|BBB|CCC))+$") fails for line: 2, column: LastName, value: "blah"
FAIL
```

And just to confirm the magic quotes (“ and ”) are just being added by your browser and not what you have verbatim in the schema?

**Comment by seanhenry1996** [comment]
yeah @luketebbs that was the case, the regex was fine. i had written down the whole thing in my notes and it was adding the quotes as “ and not ". It works fine for me now. Thank you

**Comment by seanhenry1996** [comment]
Hey guys, i wanted to check in on the progress of a new release for this bug fix. Is there an updated timeline on when to expect the new release?

**Pull request merged**
