### PR TITLE
Imporved Streams handling further for BOM

### PR DESCRIPTION
**Pull request by adamretter**

### CODE REVIEW

**Comment by adamretter** [comment]
@rhubner @LauraDamianTNA @DavidUnderdown Bing Bong! Any updates please?

**Comment by adamretter** [comment]
@DavidUnderdown It's been 6 months, can we get this merged?

**Comment by DavidUnderdown** [comment]
Adam the CI tests are not passing.

**Comment by adamretter** [comment]
@DavidUnderdown So the situation is the same as always. i.e. Travis-CI passes fine (Linux), whilst AppVeyor (Windows) fails. The CSV Validator has some known problems with Windows platforms which have been outstanding for a very long time. See - https://github.com/digital-preservation/csv-validator/pull/158

As the Linux tests on Travis continue to pass, I believe this PR can be merged.

**Pull request merged**
