### PR TITLE
[feature] Implemented integrity check functionality

### PR DESCRIPTION
**Pull request by valydia**
Basically the current version of the CSV validator, provides rules to check that each file listed in the metadata actually exist on the drive. The integrity check provides the complementary functionality, namely, ensuring that each file present on the drive is actually listed in the metadata. This can be useful when we'd like to detect unwanted additional (sometimes hidden) files present on the drive. To use this feature with the command line we need to add the option -i (or --integrity-check) with the name of the filepath column in the metadata schema, for exemple, given some metadeta where the filepath column is named "identifier", the command we'll be:

./validate -i identifier $csv-path $csv-schema-path

### CODE REVIEW

**Comment by adamretter** [comment]
I think there are some problems with this feature:

It does not fit well with the existing concept of file paths in CSV Schema...

For example file path construction from within the CSV for integrity checks can be based on a composite of several CSV fields for example when using the [file-exists](http://digital-preservation.github.io/csv-schema/csv-schema-1.0.html#file-exists-expressions) expression, you can reference a second field as the base field through `StringProvider`. Other similar field operations such as `checksum` also allow such functionality.

Unfortunately the *integrity check* functionality that was added seems to have missed this concept, and so it will not work for many CSV files, including I might add, the CSV files generated by the National Archives own Scanning and Transcription framework... unless I am mistaken?

**Comment by DavidUnderdown** [comment]
This is a command line switch or option in the GUI, rather than a part of the schema language as such, so I'm not sure it is applicable?

**Comment by adamretter** [comment]
Yes I realise it is a command line switch, but it is impossible to determine the integrity of a drive from the CSV file without knowing how file paths are construed in the CSV file itself. The current attempt rather assumes that the entire absolute file path will appear in a single column. This is often not the case, and is certainly not the case in the Scanning and Transcription framework.

For example, consider the CSV:
```
f1,f2
abc,0001.jp2
xyz,0001.jp2
```

or the CSV:
```
id, f2,
1,0001.jp2
2,0001.jp2
```

and the disk layout:
```
/
/metadata
/metadata/metadata.csv
/content
/content/absgs/shsgsg/abc/0001.jp2
/content/absgs/shsgsg/xyz/0001.jp2
```

In both instances there is no way that the current integrity check functionality could give you a definitive pass or fail result.

**Comment by DavidUnderdown** [comment]
It's sufficiently true for the STF case, any path substitution defined is also applied for the integrity check.  But for the general case more work is needed

**Comment by adamretter** [comment]
Yes I understand path substitutions are applied, but I thought in STFF, there was also the case that file paths were built up from one or more columns? Or perhaps that changed?

**Comment by DavidUnderdown** [comment]
No, we always had a single full filepath

**Comment by adamretter** [comment]
Okay, that's good then... perhaps it was Home Guard?!?

**Comment by DavidUnderdown** [comment]
May still be worth combining this with my Issue #63 where I simply suggested outputting the number of lines processed as part of the final report.

**Pull request merged**
