### PR TITLE
Fixes to get CI working again

### PR DESCRIPTION
**Pull request by luketebbs**
- removes unneeded scalaz-concurrent lib
- inlined header configuration

### CODE REVIEW

**Comment by luketebbs** [comment]
So it seems to now be working with *nix OS's, but not with Windows ones (perhaps AppVeyor is Windows?). 
There seems to be hard coded unix path separators in the core which won't help. 
I'll dig out a Windows machine and attempt to reproduce - I'm closing down this PR in the meantime.

**Comment by luketebbs** [comment]
I've resurrected a windows machine to run the tests on. I was hoping it was just a hard coded path separator somewhere but it looks like it's a bit more involved - I think the bug resides in the FileSystem class or some code connected to it. 
I'll continue tracking it down but I think it may be worth merging these fixes in in the meantime.

**Comment by adamretter** [comment]
@luketebbs would it be possible to split apart the build/CI fixes from removing Scalaz into separate PRs to make it easier to review and merge?

**Comment by luketebbs** [comment]
They are already two separate PR's. 

This PR only removes scalaz-concurrent which as it's defined in the parent POM but not used in any of the modules causes maven to complain and therefore CI to fail.

**Comment by adamretter** [comment]
@luketebbs Thanks I think this looks good in the most part.

Just one question, now that you have removed `<artifactId>oss-parent</artifactId>` as the parent (which is actually recommended these days) - do we still meet the requirements of uploading to Maven Central? It may be that some metadata/plugins that were in the oss-parent pom now need to be added directly to our `pom.xml`?

**Comment by luketebbs** [comment]
I'm not aware of any requirements that will be broken by these changes. I opened up the built jars for the core both for master and for this branch. They have the same manifest (except for checksums) and the packaged POM's look the same aside from differences you'd expect (like the cifix one not have scalaz-concurrent in it). 

So I think we're safe to proceed. If however it does turn out I'm wrong (and I could be - I don't know what AppVeyor is doing behind the scenes) I still think we're moving in the right direction with this change (we can't deploy at the moment with the test failures), and if maven central rejects it they usually give a reason why so we can examine and fix.

**Pull request merged**
