### PR TITLE
Add explicit row line number and column index to the FailMessage.

### PR DESCRIPTION
**Pull request by ivanfrolovmd**
In our project we need an explicit line number and column index in the Error Message as opposed to the reference inside the message string. Maybe it could be of value to others as well.

### CODE REVIEW

**Comment by adamretter** [comment]
@ivanfrolovmd At a glance this looks good. It will take me a bit of time to review it in detail though. One question though, which I could probably figure out if I delve into the code... but why is the default column index now -1?

**Comment by ivanfrolovmd** [comment]
Some error messages don't have column index assigned, I wasn't sure what would be the value in Java API for this case, so chose the number outside the range of possible values (-1).

**Comment by adamretter** [comment]
@ivanfrolovmd Perhaps better to use `Option` then?

**Comment by ivanfrolovmd** [comment]
Yes, probably `Option` is better in Scala, and then translate it to `-1` (int) or `null` (Integer) in Java API bridge.

**Comment by adamretter** [comment]
@ivanfrolovmd Okay cool, if you update the pull request then I will merge.

**Comment by ivanfrolovmd** [comment]
@adamretter, I've updated the code to use `Option`s. Please, review.

**Comment by adamretter** [comment]
Excellent stuff, thank you very much @ivanfrolovmd. In future I might try to also revise FailMessage so that the line numbers and column numbers are not included in the textual message itself. We could also provide codes for each error, but this should probably be dictated by a new edition of the CSV Schema Specification.

**Pull request merged**
