### PR TITLE
added a cache to store compiled regex and stopped storing success mes…

### PR DESCRIPTION
**Pull request by JessFlan**
…sages to reduce memory usage

See this page for details on the speed and memory enhancements:
https://github.com/JessFlan/csv-validator/wiki/Speed-testing

### CODE REVIEW

**Comment by DavidUnderdown** [comment]
Thanks @JessFlan this looks really useul, and may help address #130.  I've assigned this to a couple of our devs for review

**Comment by adamretter** [comment]
@JessFlan Thank you for this excellent contribution. I have manually merged it to master as I wanted to exclude the image files and cleanup the whitespace in the code. Your contribution is much appreciated and I am very excited about the performance increase that you have found.

**Comment by JessFlan** [comment]
I'm glad it is useful.  Are their any plans to do a release soon?  It would be nice to have a built version that works for very large files available here: http://search.maven.org/#search%7Cga%7C1%7Ccsv-validator

**Comment by adamretter** [comment]
@JessFlan I expect that @DavidUnderdown or @LauraDamianTNA could best tell you that...

**Pull request closed without merging**
