### PR TITLE
Bug fixes around warnings and general maintenance.

### PR DESCRIPTION
**Pull request by adamretter**
1) Makes sure that the command line exits with the appropriate error code when warnings are encountered.

2) Makes sure warnings are also displayed by the fail-fast validator (that is if they are encountered before the first error).

### CODE REVIEW

**Comment by DavidUnderdown** [comment]
Does the test version you supplied previously ahve all these changes in?

**Comment by adamretter** [comment]
All apart from  692a401 and two test-cases added to 31e21c2

**Comment by adamretter** [comment]
So @DavidUnderdown and @LauraDamianTNA any chance of getting this merged?

**Comment by adamretter** [comment]
Actually 2 secs - I want to land this one first (which I am just testing) https://github.com/digital-preservation/csv-validator/pull/75

**Comment by adamretter** [comment]
@DavidUnderdown and @LauraDamianTNA Okay it's now ready for you to merge...

**Pull request merged**
